print("Mone, ninnod njan paranjathalle jeeviche pattu nnu?")
print("Pakshe nee ennum ingane aavum. Oru maatatavumilla.")
print("Ennanu anthyamennu enikkariyilla.")
num = int(input("Akkam thaada: "))
print(num)